### ISSUE TITLE
Add the ability to specify where to save quicklook plots

### ISSUE THREAD

**Issue by ziotom78** [satorchi/qubicpack#2]
Currently, the function `quicklook` [hardcodes the name of the file](https://github.com/satorchi/qubicpack), which is always saved in the current directory. It would be nice to provide a keyword to the `quicklook` function to allow the user to specify the pathname. The default could be `None`, in which case the code should continue using the existing solution; moreover, it would preserve compatibility with existing codes.

This would be helpful to fix bug [#14](https://github.com/ziotom78/qutedb/issues/14) in [QuteDB](https://github.com/ziotom78/qutedb).

**Comment by satorchi** [comment]
I've added the requested keywords.  I also added the "savedir" keyword if you only want to specify the directory where the image file is saved.

For figsize, note that the intention is to have the quicklook fit on A4 size paper, so the figsize aspect ratio should be approximately 210x280
